### ISSUE TITLE
按照流程遇到了一些问题

### ISSUE THREAD

**Issue by windy1021** [superggfun/smoba#15]
不知道这个项目目前是否还能使用？按流程跑了一遍遇到了一点问题，又重新排查了好几遍还是不知道怎么解决，不知道是不是版本不适配还是什么，能不能麻烦作者大大帮忙看一下
1、在[ssl.kohsocialapp.qq.com/user/login](https://ssl.kohsocialapp.qq.com/user/login)中没有找到“accessToken”，找了其他user目录下发现一个“token”，不知道是否可以代替
2、在华为云创建函数时没有选择FunctionGraph版本的选项，是否保持默认就可以？还是我哪里操作有问题导致错过了这个选项？
3、运行一遍后返回“runtime bootstrap file is not found”，但由于以上两个问题我也排查不出来到底哪里出错了

谢谢大佬

**Comment by superggfun** [comment]
现在仍然是可以正常使用的，能否截图一下提供一下更多信息。

**Comment by windy1021** [comment]
> 现在仍然是可以正常使用的，能否截图一下提供一下更多信息。

谢谢大佬，现在成功了。accessToken下载了一个老版本的抓到了，然后发现zip用的的Windows的😂现在没问题啦

**Comment by superggfun** [comment]
好的，如果有任何问题可以提问

**Comment by windy1021** [comment]
> 好的，如果有任何问题可以提问

大佬辛苦了，还有个问题想问下就是是否支持推送到TGbot？可以的话要怎么设置呢

**Comment by superggfun** [comment]
目前只能使用微信推送

南风 ***@***.***> 于2023年5月29日周一 10:00写道：
