### ISSUE TITLE
任务完成但奖励礼包不到账

### ISSUE THREAD

**Issue by zxsczx** [superggfun/smoba#2]
大佬好，按教程走做完任务也领取完礼包了，但例如钻石、铭文碎片这些礼包没有进账号邮箱，是哪里出了问题，感谢！
账号是Ios QQ区

**Comment by superggfun** [comment]
你IOS系统的是如何运行这些的，我教程都是安卓的啊

**Comment by zxsczx** [comment]
> 你IOS系统的是如何运行这些的，我教程都是安卓的啊

同样也是抓包然后挂云函数，我以为原理是相通的，结果发现东西不到账但是任务做完了

**Comment by superggfun** [comment]
我有时间再看看

**Comment by superggfun** [comment]
解决问题中...

**Comment by superggfun** [comment]
已经重构，并修复了
