### ISSUE TITLE
老哥，知道怎么获取游戏历史记录吗

### ISSUE THREAD

**Issue by PoetGcc** [superggfun/smoba#3]
想获取指定id的游戏历史记录

**Comment by superggfun** [comment]
可以，但是他历史记录需要打开。

**Comment by PoetGcc** [comment]
> 可以，但是他历史记录需要打开。

老哥，可以加个微信不？请教请教你，我245304237

**Comment by PoetGcc** [comment]
老哥，通过你博客的qq联系你了，等你有空了，想请教你下

**Comment by PoetGcc** [comment]
245304237，我在qq上给你消息了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月6日(周一) 晚上10:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [superggfun/smoba] 老哥，知道怎么获取游戏历史记录吗 (Issue #3)




 
哪个个是你QQ

**Comment by superggfun** [comment]
没有看到消息

**Comment by PoetGcc** [comment]
我qq245304237，老哥，麻烦加我下吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月17日(周五) 晚上8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [superggfun/smoba] 老哥，知道怎么获取游戏历史记录吗 (Issue #3)




 
没有看到消息

**Comment by superggfun** [comment]
搜不到

**Comment by PoetGcc** [comment]
你说下你的，老哥



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月19日(周日) 下午4:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [superggfun/smoba] 老哥，知道怎么获取游戏历史记录吗 (Issue #3)




 
搜不到
