### ISSUE TITLE
这种抓包到的参数会过期吗？

### ISSUE THREAD

**Issue by youkoulc** [superggfun/smoba#4]
如果会的话，为方便及时更新参数，可以考虑在签到后通过pushplus等平台推送通知。

**Comment by superggfun** [comment]
我尽力

**Comment by youkoulc** [comment]
> 我尽力

不过用了这么久倒是一直没失效过，失效频率这么低，这功能倒是需求不大了。

但签到、每日任务完成后奖励都没领，得每天手动登录APP领取，还蛮奇怪的。

**Comment by superggfun** [comment]
已经解决问题了
