### ISSUE TITLE
Something Wrong When I run the Function on Huawei Cloud

### ISSUE THREAD

**Issue by popsee** [superggfun/smoba#6]
![QQ截图20220625093409](https://user-images.githubusercontent.com/13653691/175753344-207afa99-10fe-4f7f-ab3b-73ac10b99c36.png)
大佬，我按照教程填了两个账号的config.json的参数，丢到华为云上建个测试模板运行，然后报错了！
函数返回
runtime bootstrap file is not found
错误码
FSS.4202
场景描述
函数找不到 bootstrap 文件。
解决方案
请检查 bootstrap 脚本文件路径配置是否正确。

不怎么了解go语言，所以没法改源码，还请大佬支援下，这个错误如果修复或屏蔽掉
能跑起来就行！拜托了！

**Comment by popsee** [comment]
![555](https://user-images.githubusercontent.com/13653691/175753603-324c446c-93dc-4612-9151-f92f8906c5da.png)
This was detail error!

**Comment by popsee** [comment]
直接跑定时器回看日志也没为空。it's so weird!
![image](https://user-images.githubusercontent.com/13653691/175753666-936eb719-51fb-41de-8281-39615693653d.png)

**Comment by popsee** [comment]
直接跑定时器回看日志也没为空。it's so weird!
![image](https://user-images.githubusercontent.com/13653691/175753724-d682ca3a-db0a-48ba-8efb-10a2a60df08d.png)

**Comment by superggfun** [comment]
![image](https://user-images.githubusercontent.com/89253691/175810417-86480602-73b9-486c-94fd-4c519b6c2da4.pngga)
上传的文件夹感觉很奇怪，有个linux。
压缩文件路径是这样的
![image](https://user-images.githubusercontent.com/89253691/175810518-c49805a2-d586-434a-8b62-ce9cb732a9cb.png)
上传之后路径显示是这样的
![image](https://user-images.githubusercontent.com/89253691/175810549-f4cef23c-a881-41b0-81d8-d8e46c5c984b.png)
你可能多了一个linux路径下。

**Comment by popsee** [comment]
![image](https://user-images.githubusercontent.com/13653691/175935593-d8122e68-053a-46bd-97ce-5089cc377a26.png)
感谢老哥的指导，确实是路径的问题，之前自己重新压缩zip包多了个文件夹，导致程序没法执行，这个坑真的的坑，好在大佬慧眼通天，明察秋毫，一下子就找到了bug所在！
再次表示感谢！
特别要感谢大佬的高质量文档教程，尤其对小白用户特别友好，cookie抓取写的特别详细，定位的也相当精准，不想某些代码抓cookie直接把请求上的cookie一堆全糊上去，好多没有的就感觉特别难受，大赞一个！very nice！
